### ISSUE TITLE
JMnedict name dictionary support

### ISSUE THREAD

**Issue by aehlke** [neocl/jamdict#10]
It would be great if this had unified access to JMnedict as well.

**Comment by letuananh** [comment]
Thanks for comment. Actually I'm working on this enhancement. Hopefully it will be available soon.

**Comment by mosesweb** [comment]
I am curious how the situation looks with support for JMnedict.

**Comment by letuananh** [comment]
Good day,
Sorry I didn't have time to look into this for a while. I'm still working on this. Since there are several people requested for this feature I'll try to have a release really soon :)

**Comment by letuananh** [comment]
@mosesweb I have just released jamdict 0.1a7 on PyPI with JMnedict support. Please give it a try. Thanks you :)

**Comment by letuananh** [comment]
https://github.com/neocl/jamdict/releases/tag/0.1a7

**Comment by mosesweb** [comment]
@letuananh I am very excited about this and will surely try it out!
