### ISSUE TITLE
how to reset the sqlite 3 database

### ISSUE THREAD

**Issue by AronWater** [neocl/jamdict#14]
There is some error while importing the file [gdrive](https://drive.google.com/drive/folders/1z4zF9ImZlNeTZZplflvvnpZfJp3WVLPk)

Which make it doesn't find any character

![image](https://user-images.githubusercontent.com/36737465/77858097-de7f3a80-7233-11ea-8673-ff5972352181.png)

May I know where is the database storing at, how do reset them or delete them

**Comment by letuananh** [comment]
Here is the link to compiled SQLite database:
https://drive.google.com/open?id=1H9TLKO4d1iySOPsXwWRnEyX-BbCh1O3E
