### ISSUE TITLE
Customizing JAMDICT_HOME / JAMDICT_DATA

### ISSUE THREAD

**Issue by didmar** [neocl/jamdict#15]
I'm using jamdict for an educational game and I would like to install jamdict's data in a custom folder.
After looking at `jamdict.config`, I've tried setting environment variables `JAMDICT_HOME` and `JAMDICT_DATA`, be this seems to have no effect.
Is there a proper way to do this ?

**Comment by letuananh** [comment]
Hi, jamdict is configured using a configuration file and not environment variable in the current version. You can check the location of the configuration file using:
```bash
python3 -m jamdict.tools info
```

**Comment by didmar** [comment]
Thank you for clarifying that !
