### ISSUE TITLE
Some words not searchable in dictionary

### ISSUE THREAD

**Issue by thinkingbox12** [neocl/jamdict#26]
I am finding that a word that should be in the dictionary (for example, 大事にする（だいじにする）) is not showing up in the dictionary. Not sure why this is- it can be seen in the JMDictDB [here](https://www.edrdg.org/jmdictdb/cgi-bin/entr.py?svc=jmdict&sid=&q=2837822)

**Comment by letuananh** [comment]
Thank you for discovering that. It turned out that I use outdated XML source files to generate the database so newer entries like this are missing. I have recompiled the database and updated both [jamdict-data](https://pypi.org/project/jamdict-data/) package and the [Google drive folder](https://drive.google.com/drive/u/1/folders/1z4zF9ImZlNeTZZplflvvnpZfJp3WVLPk).

```bash
$ pip install jamdict jamdict-data==1.5
....
Successfully installed chirptext-0.1a20 jamdict-0.1a8 jamdict-data-1.5 puchikarui-0.1a3

(.env) [jamtest]$ python -m jamdict lookup id#2837822
========================================
Found entries
========================================
Entry: 2837822 | Kj:  大事にする | Kn: だいじにする
--------------------
1. to take good care of/to treasure/to value/to hold dear/to prize/to cherish ((expressions (phrases, clauses, etc.)|suru verb - included))

========================================
Found characters
========================================
Char: 大 | Strokes: 3
--------------------
Readings: da4, dai4, dae, da, tae, 대, 다, 태, Đại, Thái, ダイ, タイ, おお-, おお.きい, -おお.いに
Meanings: large, big
Char: 事 | Strokes: 8
--------------------
Readings: shi4, sa, 사, Sự, ジ, ズ, こと, つか.う, つか.える
Meanings: matter, thing, fact, business, reason, possibly

No name was found.
(.env) [jamtest]$ python -m jamdict lookup "大事にする"
========================================
Found entries
========================================
Entry: 2837822 | Kj:  大事にする | Kn: だいじにする
--------------------
1. to take good care of/to treasure/to value/to hold dear/to prize/to cherish ((expressions (phrases, clauses, etc.)|suru verb - included))

========================================
Found characters
========================================
Char: 大 | Strokes: 3
--------------------
Readings: da4, dai4, dae, da, tae, 대, 다, 태, Đại, Thái, ダイ, タイ, おお-, おお.きい, -おお.いに
Meanings: large, big
Char: 事 | Strokes: 8
--------------------
Readings: shi4, sa, 사, Sự, ジ, ズ, こと, つか.う, つか.える
Meanings: matter, thing, fact, business, reason, possibly

No name was found.
```

**Comment by thinkingbox12** [comment]
@letuananh Thanks for taking a look at this. I have followed the instructions and I was able to successfully update.

```
C:\Users\thinkingbox12> pip install jamdict jamdict-data==1.5
Requirement already satisfied: jamdict in c:\users\nick\appdata\local\programs\python\python39\lib\site-packages (0.1a8)
Requirement already satisfied: jamdict-data==1.5 in c:\users\nick\appdata\local\programs\python\python39\lib\site-packages (1.5)
Requirement already satisfied: chirptext>=0.1a19 in c:\users\nick\appdata\local\programs\python\python39\lib\site-packages (from jamdict) (0.1a20)
Requirement already satisfied: puchikarui>=0.1a3 in c:\users\nick\appdata\local\programs\python\python39\lib\site-packages (from jamdict) (0.1a3)
```
However, the dictionary entry still does not appear.
```
# Create an instance of Jamdict
jam = Jamdict()
print("Jamdict DB file: {}".format(jam.db_file))

# Lookup by kana
result = jam.lookup('大事にする')
for entry in result.entries:
    print(entry)

daijinisuru = jam.lookup('id#2837822').entries[0]
```
Output:
```
Jamdict DB file: C:\Users\thinkingbox12\.jamdict\data\jamdict.db
-----------------
Traceback (most recent call last):
  File "c:\Users\thinkingbox12\Desktop\dicttest.py", line 55, in <module>
    daijinisuru = jam.lookup('id#2837822').entries[0]
IndexError: list index out of range
```
Also, I was curious on the custom data files. Are those only attainable through coping the original tar.gz by hand into the folder? I.e., is a normal user that just installs from terminal supposed to be able to have all the [OK] next to all the file names? Or just only when you download and copy by hand?
Thank you

**Comment by letuananh** [comment]
Ah, I'm sorry I should have mentioned this earlier. Jamdict always use the custom database in the config file instead of the one in `jamdict-data` package. In the output you shared above it appears that you are using the old database version

```python
C:\Users\thinkingbox12\.jamdict\data\jamdict.db
```

If you delete that database file Jamdict will use the jamdict-data package and you will have access to the new database. The [OK] mark which files that are "customized" (installed manually by users). If you see jamdict.db [OK] it means that you are using a manually installed database file.

Hope this helps. Please let me know if it works for you.

**Comment by thinkingbox12** [comment]
Fixed! Thanks!
